import {Router} from 'express';
import { placeRobot, placeTask, simulationSetUp, selectStrategy, getSetupState,start, pause, resume, reset, speed} from '../controllers/simulationController';
const router= Router();
router.post("/setUp/:id", simulationSetUp);
router.post("/placeRobot",placeRobot);
router.post("/placeTask",placeTask);
router.post("/selectStrategy",selectStrategy);
router.get("/getSetupState",getSetupState);
router.post("/control/start",start);
router.post("/control/pause",pause);
router.post("/control/resume",resume);
router.post("/control/reset",reset);
router.post("/control/speed",speed);
export default router;