import {Router} from 'express';
import {  placeRobot, simulationSetUp } from 'src/controllers/simulationController';
const router= Router();
router.post("/setUp/:id", simulationSetUp);
router.post("/placeRobot",placeRobot);
router.post("/placeTask");
router.post("/selectStrategy");
router.post("/resetSetup");
router.get("/getSetupState");
export default router;