
export const DEFAULT_ROBOT_MAX_BATTERY = 100;
export const DEFAULT_MOVEMENT_COST_PER_CELL = 1; 
export const INITIAL_CONSECUTIVE_WAIT_STEPS = 0;
export const LOW_BATTERY_THRESHOLD = 20; 
export const ROBOT_MAX_CONSECUTIVE_WAIT_STEPS_FOR_REPATH = 3; 
export const CHARGING_DURATION_STEPS = 5; 
export const DEFAULT_TASK_WORK_DURATION = 3; 
export const DEFAULT_BATTERY_COST_TO_PERFORM_TASK = 2; 
export const DEFAULT_SIMULATION_SPEED_FACTOR = 1.0; 
export const BASE_SIMULATION_STEP_INTERVAL_MS = 1000; 

export const DEFAULT_ROBOT_ICON = 'robot_icon_green.png'; 